@startuml
'https://plantuml.com/class-diagram

HeroAircraft --> HeroAircraft
Game --> HeroAircraft

class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    - instance:HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<BaseBullet>
    + getInstance():HeroAircraft
}
class Game


@enduml